version: '3'
services:
  docker:
    image: docker
    container_name: docker
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  spring-boot-docker:
    image: spring-boot-docker
    container_name: spring-boot-docker
    build:
      context: ./spring-boot-docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"